endpoints:
  - path: /hello/{id:number}/hi/{e:string}/uu
    contentType: application/json
    method: post
    payload: '{
                  "glossary": {
                      "title": "example - ${id} - ${e} glossary",
              		"GlossDiv": {
                          "title": "S",
              			"GlossList": {
                              "GlossEntry": {
                                  "ID": "SGML",
              					"SortAs": "SGML",
              					"GlossTerm": "Standard Generalized Markup Language",
              					"Acronym": "SGML",
              					"Abbrev": "ISO 8879:1986",
              					"GlossDef": {
                                      "para": "A meta-markup language, used to create markup languages such as DocBook.",
              						"GlossSeeAlso": ["GML", "XML"]
                                  },
              					"GlossSee": "markup"
                              }
                          }
                      }
                  }
              }'
  - path: /hullo
    contentType: application/xml
    payload: '<?xml version="1.0" encoding="UTF-8"?>
              <note>
                <to>Tove</to>
                <from>Jani</from>
                <heading>Reminder</heading>
                <body>Don''t forget me this weekend!</body>
               </note>'
  - path: /htmlll
    contentType: text/html
    payload: '
      <h1>This is a big heading</h1>
      <img src="https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" />
    '