endpoints:
  - path: /hello
    contentType: application/json
    payload: '{
                  "glossary": {
                      "title": "example glossary",
              		"GlossDiv": {
                          "title": "S",
              			"GlossList": {
                              "GlossEntry": {
                                  "ID": "SGML",
              					"SortAs": "SGML",
              					"GlossTerm": "Standard Generalized Markup Language",
              					"Acronym": "SGML",
              					"Abbrev": "ISO 8879:1986",
              					"GlossDef": {
                                      "para": "A meta-markup language, used to create markup languages such as DocBook.",
              						"GlossSeeAlso": ["GML", "XML"]
                                  },
              					"GlossSee": "markup"
                              }
                          }
                      }
                  }
              }'
  - path: /hullo
    contentType: application/xml
    payload: '<?xml version="1.0" encoding="UTF-8"?>
              <note>
                <to>Tove</to>
                <from>Jani</from>
                <heading>Reminder</heading>
                <body>Don''t forget me this weekend!</body>
               </note>'